---
title: "OLE_analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{OLE_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, message=FALSE, warning=FALSE, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE, warning=FALSE}
library(rdborrow)
set.seed(2023)
```


## 1. Simulate a cross-over study

We first simulate a cross-over study:

```{r message=FALSE, warning=FALSE}
# separate is better: could be another S
# TODO: checking the same number of dimension

# S = 1
X_int = simulate_X_dct_mvnorm(n = 50,   # number of units
                              p = 4,    # dimension of variables
                              mu = rep(1, 4),  # population mean of multivariate normal
                              sig = diag(4),   # population covariance matrix of mv normal
                              cat_cols = c(1, 2), # which columns are categorical
                              cat_prob = list(c(0.3, 0.7), c(0.4, 0.6)) # the pdf of categorical variables 
)

# S = 0
X_ext = simulate_X_dct_mvnorm(n = 50,   # number of units
                              p = 4,    # dimension of variables
                              mu = rep(0, 4),  # population mean of multivariate normal
                              sig = diag(4),   # population covariance matrix of mv normal
                              cat_cols = c(1, 2), # which columns are categorical
                              cat_prob = list(c(0.3, 0.7), c(0.4, 0.6)) # the pdf of categorical variables 
)
```


```{r message=FALSE, warning=FALSE}
# Specify outcome models after OLE
# clarify certain format of the dataset
model_form_x_t1 = "x1*1 + x2*1 + x3*1 + x4*1"
model_form_x_t2 = "x1*1 + x2*(-1) + x3*(-1) + x4*1"
model_form_x_t3 = "x1*1 + x2*1 + x3*1 + x4*1"
model_form_x_t4 = "x1*1 + x2*(-1) + x3*(-1) + x4*1"

outcome_model_specs = list(
  list(effect = 3, model_form_x = model_form_x_t1, noise_mean = 0, noise_sd = 0.5),  # model form for the first time point, given by model_form1
  list(effect = 3, model_form_x = model_form_x_t2, noise_mean = 0, noise_sd = 0.5),  # model form for the second time point, given by model_form2
  list(effect = 5, model_form_x = model_form_x_t3, noise_mean = 0, noise_sd = 0.5),  # model form for the third time point, given by model_form3
  list(effect = 5, model_form_x = model_form_x_t4, noise_mean = 0, noise_sd = 0.5)   # model form for the fourth time point, given by model_form4
)


Data = simulate_trial(X_int,   # simulated covariates for internal study
                      X_ext,   # simulated covariates for external study
                      prob_treated = 2/3, # treatment probability for two periods
                      OLE_flag = T,
                      T_cross = 2,  # follow up time within each phases
                      outcome_model_specs)  # outcome models

## T_cross or specs, 
## pattern more tied to the treated group
## whether to separate the specs to pre/post
## 
```


```{r message=FALSE, warning=FALSE}
head(Data)
```

## 2. Analyzing the experiment using DID methods

### IPW
```{r message=FALSE, warning=FALSE}
bootstrap_obj = setup_bootstrap(
  replicates = 2000, 
  bootstrap_CI_type = "perc" 
)

method_DID_obj = setup_method_DID(method_name = "IPW",
                          bootstrap_flag = T,
                          model_form_piS = "S ~ x1 + x2 + x3 + x4",
                          model_form_piA = "A ~ x1 + x2 + x3 + x4")

analysis_OLE_obj = setup_analysis_OLE(
  data = Data,
  trial_status_col_name = "S", 
  treatment_col_name = "A", 
  outcome_col_name = c("y1", "y2", "y3", "y4"), 
  covariates_col_name = c("x1", "x2", "x3", "x4"),
  T_cross = 2,
  method_OLE_obj = method_DID_obj)

run_analysis(analysis_OLE_obj, quiet = F)

```

### AIPW
```{r message=FALSE, warning=FALSE}
model_form_mu = c("y1 ~ x1 + x2 + x3 + x4", 
                  "y2 ~ x1 + x2 + x3 + x4",
                  "y3 ~ x1 + x2 + x3 + x4",
                  "y4 ~ x1 + x2 + x3 + x4")

method_DID_obj = setup_method_DID(method_name = "AIPW",
                                  bootstrap_flag = T,
                                  model_form_piS = "S ~ x1 + x2 + x3 + x4",
                                  model_form_piA = "S ~ x1 + x2 + x3 + x4",
                                  model_form_mu0_ext = model_form_mu)

analysis_OLE_obj = setup_analysis_OLE( 
  data = Data, 
  trial_status_col_name = "S", 
  treatment_col_name = "A", 
  outcome_col_name = c("y1", "y2", "y3", "y4"), 
  covariates_col_name = c("x1", "x2", "x3", "x4"), 
  T_cross = 2,  
  method_OLE_obj = method_DID_obj) 

run_analysis(analysis_OLE_obj) 

```


### OR
```{r message=FALSE, warning=FALSE}
model_form_mu = c("y1 ~ x1 + x2 + x3 + x4", 
                  "y2 ~ x1 + x2 + x3 + x4",
                  "y3 ~ x1 + x2 + x3 + x4",
                  "y4 ~ x1 + x2 + x3 + x4")

method_DID_obj = setup_method_DID(method_name = "OR",
                                  bootstrap_flag = T,
                                  model_form_mu0_ext = model_form_mu, 
                                  model_form_mu0_rct = model_form_mu, 
                                  model_form_mu1_rct = model_form_mu)

analysis_OLE_obj = setup_analysis_OLE(
  data = Data,
  trial_status_col_name = "S", 
  treatment_col_name = "A", 
  outcome_col_name = c("y1", "y2", "y3", "y4"), 
  covariates_col_name = c("x1", "x2", "x3", "x4"),
  T_cross = 2,
  method_OLE_obj = method_DID_obj)

run_analysis(analysis_OLE_obj)

```


### 3. Analyzing the experiment using synthetic control methods
```{r message=FALSE, warning=FALSE}
bootstrap_obj = setup_bootstrap(
  replicates = 200, 
  bootstrap_CI_type = "perc" 
)

method_SCM_obj = setup_method_SCM(method_name = "SCM", 
                                  bootstrap_flag = T, 
                                  bootstrap_obj = bootstrap_obj, 
                                  lambda.min = 0, 
                                  lambda.max = 1e-3, 
                                  nlambda = 10, 
                                  parallel = "multicore", 
                                  ncpus = 4) 

analysis_OLE_obj = setup_analysis_OLE(
  data = Data, 
  trial_status_col_name = "S", 
  treatment_col_name = "A", 
  outcome_col_name = c("y1", "y2", "y3", "y4"), 
  covariates_col_name = c("x1", "x2", "x3", "x4"), 
  T_cross = 2, 
  method_OLE_obj = method_SCM_obj) 

run_analysis(analysis_OLE_obj) 

```


