---
title: "EDA for SMA data"
output: pdf_document
date: "2023-07-14"
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
```

# Loading data
```{r}
load("~/rdborrow/Study/SMA_data_simulation.rda")
head(SMA_Xover_data)
SMA_Xover_data = na.omit(SMA_Xover_data)
```

Covariates to work with: SMA_Type + SMN2_Copy_Number + Scoliosis + Age_Enrollment + Y0 + A

## Preprocessin
```{r}
SMA_Xover_data$SMA_Type = as.factor(SMA_Xover_data$SMA_Type)
SMA_Xover_data$A = as.factor(SMA_Xover_data$A)
SMA_Xover_data$S = as.factor(SMA_Xover_data$S)
SMA_Xover_data$SMN2_Copy_Number = as.integer(SMA_Xover_data$SMN2_Copy_Number)
SMA_Xover_data$Scoliosis = as.factor(SMA_Xover_data$Scoliosis)
SMA_Xover_data$Age_Enrollment = as.integer(SMA_Xover_data$Age_Enrollment)
```


```{r}
cat("SMA_Type: \n")
summary(SMA_Xover_data$SMA_Type)
cat("SMN2_Copy_Number: \n")
summary(SMA_Xover_data$SMN2_Copy_Number)
cat("Scoliosis: \n")
summary(SMA_Xover_data$Scoliosis)
cat("Age_Enrollment: \n")
summary(SMA_Xover_data$Age_Enrollment)
cat("Y0: \n")
summary(SMA_Xover_data$Y0)
cat("A: \n")
summary(SMA_Xover_data$A)
cat("S: \n")
summary(SMA_Xover_data$S)
```

```{r}
SMA_Xover_data %>% 
  group_by(S, SMA_Type, Scoliosis, SMN2_Copy_Number) %>%
  summarize(n())
```


```{r}
A = SMA_Xover_data$A
S = SMA_Xover_data$S

Y0 = SMA_Xover_data$Y0
SMA_Type = SMA_Xover_data$SMA_Type
Scoliosis = SMA_Xover_data$Scoliosis
SMN2_Copy_Number = SMA_Xover_data$SMN2_Copy_Number

Age_Enrollment = SMA_Xover_data$Age_Enrollment
```



## Visualization
```{r}
print(table(A, S))
chisq.test(x = A, y = S)
```


```{r}
print(table(SMA_Type, S))
chisq.test(x = SMA_Type, y = S)
```

```{r}
print(table(SMN2_Copy_Number, S))
chisq.test(x = SMN2_Copy_Number, y = S)
```
```{r}
summary(aov(Y0 ~ SMN2_Copy_Number, data = SMA_Xover_data))
```


```{r}
table(Scoliosis, S)
chisq.test(x = Scoliosis, y = S)
```

```{r}
SMA_Xover_data %>% ggplot(aes(x = Age_Enrollment)) +
```


```{r}
geom_histogram(aes(fill = S, y = after_stat(density)), col = "black", bins = 20) + 
  geom_density(col = "black", adjust = 0.5) +
  facet_wrap(vars(S))
  
```

```{r}
SMA_Xover_data %>% filter(S == 1) %>% ggplot(aes(x = Age_Enrollment)) + 
  geom_histogram(aes(y = after_stat(density)), col = "black", bins = 20) + 
  geom_density(col = "black", adjust = 0.8) +
  facet_grid(SMA_Type ~ Scoliosis)
  
```


```{r}
SMA_Xover_data %>% filter(S == 0) %>% ggplot(aes(x = Age_Enrollment)) + 
  geom_histogram(aes(y = after_stat(density)), col = "black", bins = 20) + 
  geom_density(col = "black", adjust = 0.8) +
  facet_grid(SMA_Type ~ Scoliosis)
```



```{r}
SMA_Xover_data %>% ggplot(aes(x = Y0)) + 
  geom_histogram(aes(fill = S, y = after_stat(density)), col = "black", bins = 20) + 
  geom_density(col = "black", adjust = 0.5) +
  facet_wrap(vars(S))
  
```

```{r}

SMA_Xover_data %>% filter(S == 1) %>% ggplot(aes(x = Y0)) + 
  geom_histogram(aes(y = after_stat(density)), col = "black", bins = 20) + 
  geom_density(col = "black", adjust = 0.5) +
  facet_grid(SMA_Type ~ Scoliosis)
  
```


```{r}

SMA_Xover_data %>% filter(S == 0) %>% ggplot(aes(x = Y0)) + 
  geom_histogram(aes(y = after_stat(density)), col = "black", bins = 15) + 
  geom_density(col = "black", adjust = 0.5) +
  facet_grid(SMA_Type ~ Scoliosis, scales = "free_y")
  
```




```{r}
library(ks)
library(rmutil)
```

```{r}
kde(SMA_Xover_data %>% filter(S == 0 & Scoliosis == 0 & SMN2_Copy_Number == 3) %>% select(Age_Enrollment, Y0))
```

```{r}
kde(rnorm(4))
```



```{r}

```




### Visualization of outcome distribution
```{r}
SMA_wide = SMA_Xover_data %>% mutate(dY0 = 0)
SMA_long = gather(SMA_wide, key = "time", value = "Y", dY0, Y1, Y2, Y3, Y4)

SMA_long

# colnames(SMA_Xover_data)
SMA_long$time = factor(SMA_long$time, levels = c("dY0", "Y1", "Y2", "Y3", "Y4"))
SMA_long = SMA_long %>% mutate(time_num = case_when(
  time == "dY0" ~ 0,
  time == "Y1" ~ 35,
  time == "Y2" ~ 52,
  time == "Y3" ~ 78,
  time == "Y4" ~ 104
))
```


```{r}
SMA_long %>% ggplot(aes(x = time_num, y = Y)) +
  geom_line(aes(group = UNI_ID), alpha = 0.8, col = "grey") + 
  geom_point(aes(group = UNI_ID)) +
  geom_smooth(method = "loess") +
  facet_wrap(~S+A) + 
  theme_gray()
```






```{r}
library(mgcv)

fit = gam(
  Y ~ SMA_Type + SMN2_Copy_Number + Scoliosis + 
    s(scale(Age_Enrollment), bs = "cr", k = 20) +
    s(scale(Y0), bs = "cr", k = 20),
  data = SMA_long %>% filter(S == 1 & time_num == 35),
  method = "REML"
    )
summary(fit)
plot(fit$fitted.values, fit$y)
```






